[package]
name = "xprojets_qcm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
stacker = "0.1.15"

[profile.dev]
opt-level = 1 # makes the debug build run 30x faster roughly